const _PTY = 'PTY';
const _LOGIN = '_LOGIN';
const _LOGOUT = '_LOGOUT';
const _EULA = '_EULA';
const _SET_EULA = '_SET_EULA';
const _FIRST_TIME_LOGIN = '_FIRST_TIME_LOGIN';
const _SET_PASSWORD = '_SET_PASSWORD';
const _POSTMAN = '_POSTMAN';
const _TOKEN_ERROR = '_TOKEN_ERROR ';
const _SHUTDOWN = '_SHUTDOWN';
const _MAIN_WIN_TITLE = '_MAIN_WIN_TITLE';
const _BROADCAST_SUBSCRIBE = '_BROADCAST_SUBSCRIBE';
const _BROADCAST_UNSUBSCRIBE = '_BROADCAST_UNSUBSCRIBE';
const _BROADCAST_RECEIVED = '_BROADCAST_RECEIVED';
const _JOIN_CHATROOM = '_JOIN_CHATROOM';
const _LEAVE_CHATROOM = '_LEAVE_CHATROOM';
const _IPC_SERVICE_ERROR = '_IPC_SERVICE_ERROR';
const _NOTIFY_RENDERER = '_NOTIFY_RENDERER';
const _CHAT_MESSAGE = '_CHAT_MESSAGE';

const PTY = Object.freeze({
  CREATE: 'CREATE_PTY',
  CREATED: 'PTY_CREATED',
  KILL: 'KILL_PTY',
  RESIZE: 'RESIZE_PTY',
  INPUT: 'PTY_INPUT',
  OUTPUT: 'PTY_OUTPUT',
  DESTROYED: 'PTY_DESTROYED'
});

export {
  _CHAT_MESSAGE,
  _NOTIFY_RENDERER,
  _MAIN_WIN_TITLE,
  _LOGIN,
  _LOGOUT,
  _EULA,
  _SET_EULA,
  _FIRST_TIME_LOGIN,
  _SET_PASSWORD,
  _POSTMAN,
  _PTY,
  _SHUTDOWN,
  _TOKEN_ERROR,
  _BROADCAST_SUBSCRIBE,
  _BROADCAST_UNSUBSCRIBE,
  _BROADCAST_RECEIVED,
  _JOIN_CHATROOM,
  _LEAVE_CHATROOM,
  _IPC_SERVICE_ERROR,
  PTY
}